apiVersion: v1
kind: Service
metadata:
  name: blog-back-service
spec:
  type: ClusterIP      # тип доступу до сервісу, ClusterIp - значення за замовчуванням і може бути пропущене
  ports:
    - port: 80         # порт по якому можна звератись до сервісу
      targetPort: 8000 # порт контейнера
  selector:
    app: blog-back     # селектор, всі Pod з даним селектором, будуть підключені до даного сервісу