apiVersion: v1
kind: Service
metadata:
  name: moderator-app-service
spec:
  type: ClusterIP      # тип доступу до сервісу, ClusterIp - значення за замовчуванням і може бути пропущене
  ports:
    - port: 81         # порт по якому можна звератись до сервісу
      targetPort: 8001 # порт контейнера
  selector:
    app: moderator-app    # селектор, всі Pod з даним селектором, будуть підключені до даного сервісу